# Generated by Django 4.0.6 on 2022-07-27 02:45

from django.db import migrations, models
from soosapp.models import Address
from django.utils import timezone

class Migration(migrations.Migration):

    initial = True
    Address.objects.all()
    address = Address(name='홍길동',addr='서울시',rdate=timezone.now())

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('addr', models.TextField()),
                ('rdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
