# Generated by Django 4.0.6 on 2022-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soosapp', '0004_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
